Traceback (most recent call last):
  File "/home/sano_anju/errlocator/sample/AssertionError/as04.py", line 4, in <module>
    assert number1 == sum(lis, 4), "Invalid Operation"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid Operation