Traceback (most recent call last):
  File "/home/sano_anju/errlocator/sample/raise/raise3.py", line 11, in <module>
    raise TypeError("bbb")
TypeError: bbb