Traceback (most recent call last):
  File "/home/sano_anju/01/sample/ValueError/v05.py", line 5, in <module>
    x, y, z = func(a)
    ^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)